//{{NO_DEPENDENCIES}}
// 生成的 Microsoft Visual C++ 包含文件。
// 由 My26518.rc 使用
//
#define IDD_ABOUTBOX				100
#define IDP_OLE_INIT_FAILED			100
#define IDR_MAINFRAME				128
#define IDR_My26518TYPE				130
#define IDD_SLOGAN_DLG				200
#define IDC_SLOGAN_TEXT				1001
#define IDC_SLOGAN_FONT_BTN			1002
#define IDC_SLOGAN_COLOR_BTN		1003
#define IDC_SLOGAN_ALIGN_LEFT		1004
#define IDC_SLOGAN_ALIGN_CENTER		1005
#define IDC_SLOGAN_ALIGN_RIGHT		1006
#define IDC_SLOGAN_VPOS				1007
#define IDC_SLOGAN_BG_BTN			1008
#define IDC_SLOGAN_SCROLL			1009
#define IDC_SLOGAN_SCROLL_INTERVAL	1010
#define ID_SET_SLOGAN				32772

// 新对象的下一组默认值
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE	310
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		310
#define _APS_NEXT_COMMAND_VALUE		32771
#endif
#endif
